"""empty message

Revision ID: 133d172e8064
Revises: 0f4b9df7d0d3
Create Date: 2022-02-23 10:11:24.457482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133d172e8064'
down_revision = '0f4b9df7d0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
